# src/main/resources/application.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pahana_billing?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update   # for dev; use 'validate' in prod
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080

app:
  security:
    jwt-secret: bXktdmVyeS1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
    jwt-expiration-ms: 86400000  # 1 day
  billing:
    tax-percent: 8.0    # configurable VAT/GST
